services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  tomcat:
    build: .
    container_name: tomcat
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
volumes:
  mysql-data: